# Generated by Django 6.0 on 2025-12-31 17:04

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Chama',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(db_index=True, help_text='Unique name for your chama group', max_length=200, verbose_name='chama name')),
                ('slug', models.SlugField(blank=True, help_text='Auto-generated URL-friendly version of the name', max_length=250, unique=True, verbose_name='slug')),
                ('description', models.TextField(blank=True, help_text='Detailed description of your chama (appears in search results)', verbose_name='description')),
                ('excerpt', models.CharField(blank=True, help_text='Short summary (max 160 chars for meta description)', max_length=160, verbose_name='excerpt')),
                ('monthly_contribution', models.DecimalField(decimal_places=2, default=1000, max_digits=10, verbose_name='monthly contribution')),
                ('contribution_day', models.IntegerField(default=1, help_text='Day of month when contributions are due (1-28)', verbose_name='contribution day')),
                ('county', models.CharField(db_index=True, help_text='County where the chama is based', max_length=100, verbose_name='county')),
                ('constituency', models.CharField(blank=True, db_index=True, max_length=100, verbose_name='constituency')),
                ('phone', models.CharField(max_length=15, verbose_name='phone')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email')),
                ('logo', models.ImageField(blank=True, help_text='Recommended size: 1200x630px for social sharing', null=True, upload_to='chama_logos/%Y/%m/%d/', verbose_name='logo')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='active')),
                ('is_public', models.BooleanField(default=False, help_text='If checked, this chama appears in public listings', verbose_name='public')),
                ('meta_title', models.CharField(blank=True, max_length=60, verbose_name='meta title')),
                ('meta_description', models.TextField(blank=True, max_length=160, verbose_name='meta description')),
                ('meta_keywords', models.CharField(blank=True, max_length=255, verbose_name='meta keywords')),
                ('total_balance', models.DecimalField(db_index=True, decimal_places=2, default=0, max_digits=12, verbose_name='total balance')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_chamas', to=settings.AUTH_USER_MODEL)),
                ('members', models.ManyToManyField(blank=True, related_name='chamas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'chama',
                'verbose_name_plural': 'chamas',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Investment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('date_invested', models.DateField()),
                ('expected_return_date', models.DateField(blank=True, null=True)),
                ('expected_return_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('actual_return_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('matured', 'Matured'), ('liquidated', 'Liquidated'), ('loss', 'Loss')], default='active', max_length=20)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('chama', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='investments', to='chama.chama')),
            ],
        ),
        migrations.CreateModel(
            name='Loan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='amount')),
                ('interest_rate', models.DecimalField(decimal_places=2, default=10.0, max_digits=5, verbose_name='interest rate (%)')),
                ('duration_months', models.IntegerField(default=1, verbose_name='duration (months)')),
                ('status', models.CharField(choices=[('PENDING', 'Pending Approval'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('DISBURSED', 'Disbursed'), ('PAID', 'Fully Paid')], db_index=True, default='PENDING', max_length=20)),
                ('request_date', models.DateTimeField(auto_now_add=True)),
                ('action_date', models.DateTimeField(blank=True, null=True)),
                ('repayment_date', models.DateField(blank=True, null=True)),
                ('action_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='processed_loans', to=settings.AUTH_USER_MODEL)),
                ('borrower', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='loans', to=settings.AUTH_USER_MODEL)),
                ('chama', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='loans', to='chama.chama')),
            ],
            options={
                'ordering': ['-request_date'],
            },
        ),
        migrations.AddIndex(
            model_name='chama',
            index=models.Index(fields=['slug', 'is_active'], name='chama_chama_slug_15e3c1_idx'),
        ),
        migrations.AddIndex(
            model_name='chama',
            index=models.Index(fields=['county', 'is_public'], name='chama_chama_county_47f178_idx'),
        ),
        migrations.AddIndex(
            model_name='chama',
            index=models.Index(fields=['created_at', 'total_balance'], name='chama_chama_created_01f5c2_idx'),
        ),
    ]
