# Generated by Django 6.0 on 2026-01-02 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chama', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='chama',
            name='contribution_frequency',
            field=models.CharField(choices=[('MONTHLY', 'Monthly'), ('WEEKLY', 'Weekly')], default='MONTHLY', max_length=10, verbose_name='contribution frequency'),
        ),
        migrations.AddField(
            model_name='chama',
            name='contribution_weekday',
            field=models.IntegerField(blank=True, choices=[(0, 'Monday'), (1, 'Tuesday'), (2, 'Wednesday'), (3, 'Thursday'), (4, 'Friday'), (5, 'Saturday'), (6, 'Sunday')], help_text='Day of the week when contributions are due', null=True, verbose_name='contribution day (weekly)'),
        ),
        migrations.AddField(
            model_name='chama',
            name='penalty_amount',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Penalty amount for late contributions', max_digits=10, verbose_name='penalty amount'),
        ),
        migrations.AddField(
            model_name='chama',
            name='penalty_grace_period',
            field=models.IntegerField(default=7, help_text='Days after contribution day before penalty applies', verbose_name='penalty grace period'),
        ),
        migrations.AlterField(
            model_name='chama',
            name='contribution_day',
            field=models.IntegerField(blank=True, default=1, help_text='Day of month when contributions are due (1-28)', null=True, verbose_name='contribution day (monthly)'),
        ),
        migrations.AlterField(
            model_name='chama',
            name='monthly_contribution',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='contribution amount'),
        ),
    ]
