# Generated by Django 6.0 on 2026-01-03 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chama', '0003_penalty'),
    ]

    operations = [
        migrations.AddField(
            model_name='chama',
            name='subscription_expiry',
            field=models.DateTimeField(blank=True, null=True, verbose_name='subscription expiry'),
        ),
        migrations.AddField(
            model_name='chama',
            name='subscription_plan',
            field=models.CharField(choices=[('BASIC', 'Starter (Free)'), ('STANDARD', 'Growth (KES 500/mo)'), ('PREMIUM', 'Enterprise (KES 1,200/mo)')], default='BASIC', max_length=20),
        ),
        migrations.AddField(
            model_name='chama',
            name='subscription_status',
            field=models.CharField(default='ACTIVE', max_length=20),
        ),
    ]
